<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\ShipClass;
use App\Models\ShipType;
use Illuminate\Database\Seeder;

class ShipClassSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $gsn = Branch::firstWhere('abbreviation', 'GSN');
        $ian = Branch::firstWhere('abbreviation', 'IAN');
        $rhn = Branch::firstWhere('abbreviation', 'RHN');
        $rmacs = Branch::firstWhere('abbreviation', 'RMACS');
        $rmmm = Branch::firstWhere('abbreviation', 'RMMM');
        $rmn = Branch::firstWhere('abbreviation', 'RMN');

        $bc = ShipType::firstWhere('abbreviation', 'BC');
        $ca = ShipType::firstWhere('abbreviation', 'CA');
        $cl = ShipType::firstWhere('abbreviation', 'CL');
        $clac = ShipType::firstWhere('abbreviation', 'CLAC');
        $cr = ShipType::firstWhere('abbreviation', 'CR');
        $dd = ShipType::firstWhere('abbreviation', 'DD');
        $dn = ShipType::firstWhere('abbreviation', 'DN');
        $hf = ShipType::firstWhere('abbreviation', 'HF');
        $jcs = ShipType::firstWhere('abbreviation', 'JCS');
        $lac = ShipType::firstWhere('abbreviation', 'LAC');
        $lf = ShipType::firstWhere('abbreviation', 'LF');
        $lph = ShipType::firstWhere('abbreviation', 'LPH');
        $mf = ShipType::firstWhere('abbreviation', 'MF');
        $pin = ShipType::firstWhere('abbreviation', 'Pin');
        $pl = ShipType::firstWhere('abbreviation', 'PL');
        $qy = ShipType::firstWhere('abbreviation', 'QY');
        $rss = ShipType::firstWhere('abbreviation', 'RSS');
        $sd = ShipType::firstWhere('abbreviation', 'SD');
        $ss = ShipType::firstWhere('abbreviation', 'SS');

        $classes = [
            [
                'name' => 'Condor',
                'type' => $pin,
                'order' => 0,
                'branches' => [$rmn, $gsn, $rhn],
                'crew_max' => 5,
                'crew_min' => 2,
                'officer_min' => 1,
            ],
            [
                'name' => 'Ferret',
                'type' => $lac,
                'order' => 1,
                'branches' => [$rmn],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Katana',
                'type' => $lac,
                'order' => 1,
                'branches' => [$rmn, $gsn],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Shrike-B',
                'type' => $lac,
                'order' => 1,
                'branches' => [$rmn, $ian],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Highlander',
                'type' => $lac,
                'order' => 1,
                'branches' => [$rmn],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Havoc',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rmn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Chanson',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rmn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Charger',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rmn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Culverin',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rmn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Javelin',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rmn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Wolfhound',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rmn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Roland',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rmn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Falcon',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rmn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Avalon',
                'type' => $cl,
                'order' => 3,
                'branches' => [$rmn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Apollo',
                'type' => $cl,
                'order' => 3,
                'branches' => [$rmn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Courageous',
                'type' => $cl,
                'order' => 3,
                'branches' => [$rmn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Kamerling',
                'type' => $cl,
                'order' => 3,
                'branches' => [$rmn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Valiant',
                'type' => $cl,
                'order' => 3,
                'branches' => [$rmn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Drake',
                'type' => $ca,
                'order' => 4,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Broadsword',
                'type' => $ca,
                'order' => 4,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Star Knight',
                'type' => $ca,
                'order' => 4,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Saganami-B',
                'type' => $ca,
                'order' => 4,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Saganami-C',
                'type' => $ca,
                'order' => 4,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Homer',
                'type' => $bc,
                'order' => 5,
                'branches' => [$rmn],
                'crew_max' => 1516,
                'crew_min' => 12,
                'officer_min' => 4,
            ],
            [
                'name' => 'Reliant',
                'type' => $bc,
                'order' => 5,
                'branches' => [$rmn],
                'crew_max' => 1516,
                'crew_min' => 12,
                'officer_min' => 4,
            ],
            [
                'name' => 'Agamemnon',
                'type' => $bc,
                'order' => 5,
                'branches' => [$rmn],
                'crew_max' => 600,
                'crew_min' => 12,
                'officer_min' => 3,
            ],
            [
                'name' => 'Unknown',
                'type' => $ca,
                'order' => 4,
                'branches' => [],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Minotaur',
                'type' => $clac,
                'order' => 8,
                'branches' => [$rmn],
                'crew_max' => 3000,
                'crew_min' => 15,
                'officer_min' => 5,
            ],
            [
                'name' => 'Unknown',
                'type' => $lac,
                'order' => 1,
                'branches' => [$rmn],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Jacob',
                'type' => $dd,
                'order' => 2,
                'branches' => [$gsn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'David',
                'type' => $cl,
                'order' => 3,
                'branches' => [$gsn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Disciple',
                'type' => $cl,
                'order' => 3,
                'branches' => [$gsn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Courvoisier',
                'type' => $bc,
                'order' => 5,
                'branches' => [$gsn],
                'crew_max' => 1516,
                'crew_min' => 12,
                'officer_min' => 4,
            ],
            [
                'name' => 'Prince Consort',
                'type' => $ca,
                'order' => 4,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Nike',
                'type' => $bc,
                'order' => 5,
                'branches' => [$rmn],
                'crew_max' => 1516,
                'crew_min' => 12,
                'officer_min' => 4,
            ],
            [
                'name' => 'Majestic',
                'type' => $dn,
                'order' => 6,
                'branches' => [$rmn],
                'crew_max' => 2566,
                'crew_min' => 16,
                'officer_min' => 5,
            ],
            [
                'name' => 'Gryphon',
                'type' => $sd,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Hydra',
                'type' => $clac,
                'order' => 8,
                'branches' => [$rmn],
                'crew_max' => 3000,
                'crew_min' => 15,
                'officer_min' => 5,
            ],
            [
                'name' => 'Medusa',
                'type' => $sd,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Medusa-B',
                'type' => $sd,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Invictus',
                'type' => $sd,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Haven',
                'type' => $sd,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Unknown',
                'type' => $ss,
                'order' => 9,
                'branches' => [],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Royal',
                'type' => $qy,
                'order' => 15,
                'branches' => [$rmn],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'NA',
                'type' => $ss,
                'order' => 9,
                'branches' => [$rmn, $gsn, $rhn],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Joshua',
                'type' => $dd,
                'order' => 2,
                'branches' => [$gsn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Paul',
                'type' => $dd,
                'order' => 2,
                'branches' => [$gsn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Harrington',
                'type' => $sd,
                'order' => 7,
                'branches' => [$gsn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Covington',
                'type' => $clac,
                'order' => 8,
                'branches' => [$gsn],
                'crew_max' => 3000,
                'crew_min' => 15,
                'officer_min' => 5,
            ],
            [
                'name' => 'Blucher',
                'type' => $bc,
                'order' => 5,
                'branches' => [$ian],
                'crew_max' => 600,
                'crew_min' => 12,
                'officer_min' => 3,
            ],
            [
                'name' => 'Seydlitz',
                'type' => $sd,
                'order' => 7,
                'branches' => [$ian],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'CourvoisierII',
                'type' => $bc,
                'order' => 5,
                'branches' => [$gsn],
                'crew_max' => 600,
                'crew_min' => 12,
                'officer_min' => 3,
            ],
            [
                'name' => 'Unknown',
                'type' => $cl,
                'order' => 3,
                'branches' => [],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Cimeterre',
                'type' => $lac,
                'order' => 1,
                'branches' => [$rhn],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Unknown',
                'type' => $lf,
                'order' => 11,
                'branches' => [],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Unknown',
                'type' => $mf,
                'order' => 12,
                'branches' => [],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Unknown',
                'type' => $hf,
                'order' => 13,
                'branches' => [],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Unknown',
                'type' => $pl,
                'order' => 14,
                'branches' => [],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Unknown',
                'type' => $cr,
                'order' => 10,
                'branches' => [$rmmm],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Frigate',
                'type' => $cl,
                'order' => 3,
                'branches' => [$rhn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Warlord-D',
                'type' => $bc,
                'order' => 5,
                'branches' => [$rhn],
                'crew_max' => 1516,
                'crew_min' => 12,
                'officer_min' => 4,
            ],
            [
                'name' => 'Dolch',
                'type' => $dd,
                'order' => 2,
                'branches' => [$ian],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Guadalcanal',
                'type' => $lph,
                'order' => 15,
                'branches' => [$rmn],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Talisman',
                'type' => $cl,
                'order' => 4,
                'branches' => [$rmn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Illustrious',
                'type' => $cl,
                'order' => 4,
                'branches' => [$rmn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Crusader',
                'type' => $ca,
                'order' => 5,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Warrior',
                'type' => $ca,
                'order' => 5,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Nightstick',
                'type' => $ca,
                'order' => 5,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Edward Saganami',
                'type' => $ca,
                'order' => 5,
                'branches' => [$rmn],
                'crew_max' => 535,
                'crew_min' => 10,
                'officer_min' => 3,
            ],
            [
                'name' => 'Redoubtable',
                'type' => $bc,
                'order' => 6,
                'branches' => [$rmn],
                'crew_max' => 1516,
                'crew_min' => 12,
                'officer_min' => 4,
            ],
            [
                'name' => 'Ad Astra',
                'type' => $dn,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 2566,
                'crew_min' => 16,
                'officer_min' => 5,
            ],
            [
                'name' => 'Royal Winton',
                'type' => $dn,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 2566,
                'crew_min' => 16,
                'officer_min' => 5,
            ],
            [
                'name' => 'Gladiator',
                'type' => $dn,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 2566,
                'crew_min' => 16,
                'officer_min' => 5,
            ],
            [
                'name' => 'Bellerophon',
                'type' => $dn,
                'order' => 7,
                'branches' => [$rmn],
                'crew_max' => 2566,
                'crew_min' => 16,
                'officer_min' => 5,
            ],
            [
                'name' => 'Samothrace',
                'type' => $sd,
                'order' => 8,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'King William',
                'type' => $sd,
                'order' => 8,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Anduril',
                'type' => $sd,
                'order' => 8,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Victory',
                'type' => $sd,
                'order' => 8,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Sphinx',
                'type' => $sd,
                'order' => 8,
                'branches' => [$rmn],
                'crew_max' => 4308,
                'crew_min' => 20,
                'officer_min' => 5,
            ],
            [
                'name' => 'Joseph',
                'type' => $dd,
                'order' => 2,
                'branches' => [$gsn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Richthofen',
                'type' => $lac,
                'order' => 1,
                'branches' => [],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Cimeterre Recon',
                'type' => $lac,
                'order' => 1,
                'branches' => [],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Cimeterre-A',
                'type' => $lac,
                'order' => 1,
                'branches' => [],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Cimeterre-B',
                'type' => $lac,
                'order' => 1,
                'branches' => [],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Voltigeur',
                'type' => $lac,
                'order' => 1,
                'branches' => [],
                'crew_max' => 25,
                'crew_min' => 3,
                'officer_min' => 1,
            ],
            [
                'name' => 'Brilliance',
                'type' => $cl,
                'order' => 4,
                'branches' => [],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Conquerer',
                'type' => $cl,
                'order' => 4,
                'branches' => [],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Guardian',
                'type' => $cl,
                'order' => 4,
                'branches' => [],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Pope',
                'type' => $cl,
                'order' => 4,
                'branches' => [$rhn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Wraith',
                'type' => $cl,
                'order' => 4,
                'branches' => [$rhn],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Floreal',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Nivose',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Durandal',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Patriotique',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Bastogne',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Breslau',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Bruges',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Desforge',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rhn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Trojan',
                'type' => $dd,
                'order' => 2,
                'branches' => [$rhn],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Bremen',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Kunlun',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Erdhummel',
                'type' => $dd,
                'order' => 2,
                'branches' => [],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Stammes',
                'type' => $dd,
                'order' => 2,
                'branches' => [$ian],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Aufhocker',
                'type' => $dd,
                'order' => 2,
                'branches' => [$ian],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Cyclop',
                'type' => $dd,
                'order' => 2,
                'branches' => [$ian],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Einhorn',
                'type' => $cl,
                'order' => 4,
                'branches' => [],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Panther',
                'type' => $cl,
                'order' => 4,
                'branches' => [],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Sternbild',
                'type' => $cl,
                'order' => 4,
                'branches' => [$ian],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Sternenbote',
                'type' => $cl,
                'order' => 4,
                'branches' => [],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Wacht',
                'type' => $cl,
                'order' => 4,
                'branches' => [],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Nachtschatten',
                'type' => $cl,
                'order' => 4,
                'branches' => [$ian],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Nebel',
                'type' => $cl,
                'order' => 4,
                'branches' => [$ian],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Vampir',
                'type' => $cl,
                'order' => 4,
                'branches' => [$ian],
                'crew_max' => 350,
                'crew_min' => 8,
                'officer_min' => 3,
            ],
            [
                'name' => 'Damon',
                'type' => $dd,
                'order' => 2,
                'branches' => [$ian],
                'crew_max' => 357,
                'crew_min' => 6,
                'officer_min' => 2,
            ],
            [
                'name' => 'Junction Control Station',
                'type' => $jcs,
                'order' => 0,
                'branches' => [$rmacs],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
            [
                'name' => 'Space Station',
                'type' => $rss,
                'order' => 0,
                'branches' => [$rmacs],
                'crew_max' => 0,
                'crew_min' => 0,
                'officer_min' => 0,
            ],
        ];

        foreach ($classes as $classToCreate) {
            $class = new ShipClass();
            $class->name = $classToCreate['name'];
            $class->type_order = $classToCreate['order'];
            $class->crew_max = $classToCreate['crew_max'];
            $class->crew_min = $classToCreate['crew_min'];
            $class->officer_min = $classToCreate['officer_min'];
            $class->shipType()->associate($classToCreate['type']);
            $class->save();
            if (sizeof($classToCreate['branches']) > 0) {
                $class->branches()->saveMany($classToCreate['branches']);
            }
        }
    }
}
